const kanji = [
  {
    kanji: "人",
    meanings: ["person", "human"],
    hiragana: "ひと",
    romanji: "hito",
  },
  {
    kanji: "一",
    meanings: ["one"],
    hiragana: "いち",
    romanji: "ichi",
  },
  {
    kanji: "行",
    meanings: ["go", "move"],
    hiragana: "いく",
    romanji: "iku",
  },
  {
    kanji: "日",
    meanings: ["day", "sun"],
    hiragana: "ひ",
    romanji: "hi",
  },
  {
    kanji: "出",
    meanings: ["exit", "leave"],
    hiragana: "でる",
    romanji: "deru",
  },
  {
    kanji: "大",
    meanings: ["big", "large"],
    hiragana: "おおきい",
    romanji: "ookii",
  },
  {
    kanji: "本",
    meanings: ["book", "origin"],
    hiragana: "ほん",
    romanji: "hon",
  },
  {
    kanji: "分",
    meanings: ["part", "minute"],
    hiragana: "ぶん",
    romanji: "bun",
  },
  {
    kanji: "年",
    meanings: ["year"],
    hiragana: "とし",
    romanji: "toshi",
  },
  {
    kanji: "書",
    meanings: ["write"],
    hiragana: "かく",
    romanji: "kaku",
  },
  {
    kanji: "中",
    meanings: ["middle", "inside"],
    hiragana: "なか",
    romanji: "naka",
  },
  {
    kanji: "時",
    meanings: ["time", "hour"],
    hiragana: "じ",
    romanji: "ji",
  },
  {
    kanji: "的",
    meanings: ["target", "adjective ending"],
    hiragana: "てき",
    romanji: "teki",
  },
  {
    kanji: "用",
    meanings: ["use", "purpose"],
    hiragana: "よう",
    romanji: "you",
  },
  {
    kanji: "作",
    meanings: ["make", "create"],
    hiragana: "つくる",
    romanji: "tsukuru",
  },
  {
    kanji: "生",
    meanings: ["life", "birth"],
    hiragana: "いきる",
    romanji: "ikiru",
  },
  {
    kanji: "数",
    meanings: ["number", "count"],
    hiragana: "かず",
    romanji: "kazu",
  },
  {
    kanji: "私",
    meanings: ["I", "private"],
    hiragana: "わたし",
    romanji: "watashi",
  },
  {
    kanji: "学",
    meanings: ["study", "learning"],
    hiragana: "まなぶ",
    romanji: "manabu",
  },
  {
    kanji: "言",
    meanings: ["say", "word"],
    hiragana: "いう",
    romanji: "iu",
  },
  {
    kanji: "文",
    meanings: ["sentence", "literature"],
    hiragana: "ぶん",
    romanji: "bun",
  },
  {
    kanji: "定",
    meanings: ["decide", "fix"],
    hiragana: "さだめる",
    romanji: "sadameru",
  },
  {
    kanji: "間",
    meanings: ["interval", "space"],
    hiragana: "あいだ",
    romanji: "aida",
  },
  {
    kanji: "合",
    meanings: ["fit", "join"],
    hiragana: "あう",
    romanji: "au",
  },
  {
    kanji: "場",
    meanings: ["place", "location"],
    hiragana: "ば",
    romanji: "ba",
  },
  {
    kanji: "子",
    meanings: ["child", "small thing"],
    hiragana: "こ",
    romanji: "ko",
  },
  {
    kanji: "入",
    meanings: ["enter", "insert"],
    hiragana: "はいる",
    romanji: "hairu",
  },
  {
    kanji: "思",
    meanings: ["think", "thought"],
    hiragana: "おもう",
    romanji: "omou",
  },
  {
    kanji: "自",
    meanings: ["self", "oneself"],
    hiragana: "じ",
    romanji: "ji",
  },
  {
    kanji: "見",
    meanings: ["see", "look"],
    hiragana: "みる",
    romanji: "miru",
  },
  {
    kanji: "者",
    meanings: ["person", "someone"],
    hiragana: "もの",
    romanji: "mono",
  },
  {
    kanji: "上",
    meanings: ["up", "above"],
    hiragana: "うえ",
    romanji: "ue",
  },
  {
    kanji: "理",
    meanings: ["reason", "logic"],
    hiragana: "り",
    romanji: "ri",
  },
  {
    kanji: "実",
    meanings: ["truth", "reality"],
    hiragana: "じつ",
    romanji: "jitsu",
  },
  {
    kanji: "方",
    meanings: ["direction", "method"],
    hiragana: "ほう",
    romanji: "hou",
  },
  {
    kanji: "会",
    meanings: ["meet", "association"],
    hiragana: "かい",
    romanji: "kai",
  },
  {
    kanji: "二",
    meanings: ["two"],
    hiragana: "に",
    romanji: "ni",
  },
  {
    kanji: "使",
    meanings: ["use", "employ"],
    hiragana: "つかう",
    romanji: "tsukau",
  },
  {
    kanji: "事",
    meanings: ["thing", "matter"],
    hiragana: "こと",
    romanji: "koto",
  },
  {
    kanji: "力",
    meanings: ["power", "strength"],
    hiragana: "ちから",
    romanji: "chikara",
  },
  {
    kanji: "表",
    meanings: ["surface", "table"],
    hiragana: "おもて",
    romanji: "omote",
  },
  {
    kanji: "前",
    meanings: ["before", "front"],
    hiragana: "まえ",
    romanji: "mae",
  },
  {
    kanji: "成",
    meanings: ["become", "achieve"],
    hiragana: "なる",
    romanji: "naru",
  },
  {
    kanji: "業",
    meanings: ["work", "industry"],
    hiragana: "ぎょう",
    romanji: "gyou",
  },
  {
    kanji: "物",
    meanings: ["thing", "object"],
    hiragana: "もの",
    romanji: "mono",
  },
  {
    kanji: "手",
    meanings: ["hand"],
    hiragana: "て",
    romanji: "te",
  },
  {
    kanji: "要",
    meanings: ["need", "important"],
    hiragana: "よう",
    romanji: "you",
  },
  {
    kanji: "動",
    meanings: ["move", "motion"],
    hiragana: "うごく",
    romanji: "ugoku",
  },
  {
    kanji: "変",
    meanings: ["change", "strange"],
    hiragana: "へん",
    romanji: "hen",
  },
  {
    kanji: "示",
    meanings: ["show", "point out"],
    hiragana: "しめす",
    romanji: "shimesu",
  },
  {
    kanji: "関",
    meanings: ["barrier", "connection"],
    hiragana: "せき",
    romanji: "seki",
  },
  {
    kanji: "図",
    meanings: ["diagram", "plan"],
    hiragana: "ず",
    romanji: "zu",
  },
  {
    kanji: "現",
    meanings: ["appear", "present"],
    hiragana: "あらわれる",
    romanji: "arawareru",
  },
  {
    kanji: "心",
    meanings: ["heart", "mind"],
    hiragana: "こころ",
    romanji: "kokoro",
  },
  {
    kanji: "明",
    meanings: ["bright", "clear"],
    hiragana: "あかるい",
    romanji: "akarui",
  },
  {
    kanji: "字",
    meanings: ["character", "letter"],
    hiragana: "じ",
    romanji: "ji",
  },
  {
    kanji: "下",
    meanings: ["below", "down"],
    hiragana: "した",
    romanji: "shita",
  },
  {
    kanji: "世",
    meanings: ["world", "generation"],
    hiragana: "せ",
    romanji: "se",
  },
  {
    kanji: "多",
    meanings: ["many", "much"],
    hiragana: "おおい",
    romanji: "ooi",
  },
  {
    kanji: "小",
    meanings: ["small", "little"],
    hiragana: "ちいさい",
    romanji: "chiisai",
  },
  {
    kanji: "今",
    meanings: ["now", "present"],
    hiragana: "いま",
    romanji: "ima",
  },
  {
    kanji: "次",
    meanings: ["next", "following"],
    hiragana: "つぎ",
    romanji: "tsugi",
  },
  {
    kanji: "館",
    meanings: ["building", "mansion"],
    hiragana: "かん",
    romanji: "kan",
  },
  {
    kanji: "選",
    meanings: ["choose", "select"],
    hiragana: "えらぶ",
    romanji: "erabu",
  },
  {
    kanji: "必",
    meanings: ["certain", "inevitable"],
    hiragana: "ひつ",
    romanji: "hitsu",
  },
  {
    kanji: "機",
    meanings: ["machine", "opportunity"],
    hiragana: "き",
    romanji: "ki",
  },
  {
    kanji: "教",
    meanings: ["teach", "faith"],
    hiragana: "おしえる",
    romanji: "oshieru",
  },
  {
    kanji: "地",
    meanings: ["earth", "ground"],
    hiragana: "ち",
    romanji: "chi",
  },
  {
    kanji: "以",
    meanings: ["since", "by means of"],
    hiragana: "い",
    romanji: "i",
  },
  {
    kanji: "語",
    meanings: ["word", "language"],
    hiragana: "ご",
    romanji: "go",
  },
  {
    kanji: "度",
    meanings: ["degree", "occurrence"],
    hiragana: "ど",
    romanji: "do",
  },
  {
    kanji: "考",
    meanings: ["think", "consider"],
    hiragana: "かんがえる",
    romanji: "kangaeru",
  },
  {
    kanji: "長",
    meanings: ["long", "chief"],
    hiragana: "ながい",
    romanji: "nagai",
  },
  {
    kanji: "初",
    meanings: ["first", "beginning"],
    hiragana: "はじめ",
    romanji: "hajime",
  },
  {
    kanji: "話",
    meanings: ["talk", "story"],
    hiragana: "はなす",
    romanji: "hanasu",
  },
  {
    kanji: "指",
    meanings: ["finger", "point"],
    hiragana: "ゆび",
    romanji: "yubi",
  },
  {
    kanji: "所",
    meanings: ["place", "location"],
    hiragana: "ところ",
    romanji: "tokoro",
  },
  {
    kanji: "集",
    meanings: ["gather", "collect"],
    hiragana: "あつめる",
    romanji: "atsumeru",
  },
  {
    kanji: "先",
    meanings: ["before", "ahead"],
    hiragana: "さき",
    romanji: "saki",
  },
  {
    kanji: "九",
    meanings: ["nine"],
    hiragana: "きゅう",
    romanji: "kyuu",
  },
  {
    kanji: "正",
    meanings: ["correct", "right"],
    hiragana: "ただしい",
    romanji: "tadashii",
  },
  {
    kanji: "第",
    meanings: ["ordinal number prefix"],
    hiragana: "だい",
    romanji: "dai",
  },
  {
    kanji: "五",
    meanings: ["five"],
    hiragana: "ご",
    romanji: "go",
  },
  {
    kanji: "切",
    meanings: ["cut", "important"],
    hiragana: "きる",
    romanji: "kiru",
  },
  {
    kanji: "有",
    meanings: ["have", "exist"],
    hiragana: "ある",
    romanji: "aru",
  },
  {
    kanji: "特",
    meanings: ["special"],
    hiragana: "とく",
    romanji: "toku",
  },
  {
    kanji: "外",
    meanings: ["outside", "foreign"],
    hiragana: "そと",
    romanji: "soto",
  },
  {
    kanji: "感",
    meanings: ["feeling", "emotion"],
    hiragana: "かん",
    romanji: "kan",
  },
  {
    kanji: "保",
    meanings: ["protect", "guarantee"],
    hiragana: "ほ",
    romanji: "ho",
  },
  {
    kanji: "山",
    meanings: ["mountain"],
    hiragana: "やま",
    romanji: "yama",
  },
  {
    kanji: "全",
    meanings: ["all", "whole"],
    hiragana: "ぜん",
    romanji: "zen",
  },
  {
    kanji: "様",
    meanings: ["appearance", "manner"],
    hiragana: "さま",
    romanji: "sama",
  },
  {
    kanji: "聞",
    meanings: ["hear", "listen"],
    hiragana: "きく",
    romanji: "kiku",
  },
  {
    kanji: "女",
    meanings: ["woman", "female"],
    hiragana: "おんな",
    romanji: "onna",
  },
  {
    kanji: "四",
    meanings: ["four"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "戦",
    meanings: ["war", "battle"],
    hiragana: "せん",
    romanji: "sen",
  },
  {
    kanji: "引",
    meanings: ["pull", "tug"],
    hiragana: "ひく",
    romanji: "hiku",
  },
  {
    kanji: "家",
    meanings: ["house", "home"],
    hiragana: "いえ",
    romanji: "ie",
  },
  {
    kanji: "国",
    meanings: ["country", "nation"],
    hiragana: "くに",
    romanji: "kuni",
  },
  {
    kanji: "内",
    meanings: ["inside", "within"],
    hiragana: "うち",
    romanji: "uchi",
  },
  {
    kanji: "代",
    meanings: ["substitute", "generation"],
    hiragana: "だい",
    romanji: "dai",
  },
  {
    kanji: "三",
    meanings: ["three"],
    hiragana: "さん",
    romanji: "san",
  },
  {
    kanji: "社",
    meanings: ["company", "society"],
    hiragana: "しゃ",
    romanji: "sha",
  },
  {
    kanji: "月",
    meanings: ["month", "moon"],
    hiragana: "つき",
    romanji: "tsuki",
  },
  {
    kanji: "十",
    meanings: ["ten"],
    hiragana: "じゅう",
    romanji: "juu",
  },
  {
    kanji: "記",
    meanings: ["record", "write"],
    hiragana: "き",
    romanji: "ki",
  },
  {
    kanji: "新",
    meanings: ["new"],
    hiragana: "あたらしい",
    romanji: "atarashii",
  },
  {
    kanji: "設",
    meanings: ["establish", "set up"],
    hiragana: "せつ",
    romanji: "setsu",
  },
  {
    kanji: "性",
    meanings: ["nature", "gender"],
    hiragana: "せい",
    romanji: "sei",
  },
  {
    kanji: "気",
    meanings: ["spirit", "energy"],
    hiragana: "き",
    romanji: "ki",
  },
  {
    kanji: "何",
    meanings: ["what"],
    hiragana: "なに",
    romanji: "nani",
  },
  {
    kanji: "画",
    meanings: ["picture", "stroke"],
    hiragana: "が",
    romanji: "ga",
  },
  {
    kanji: "対",
    meanings: ["opposite", "versus"],
    hiragana: "たい",
    romanji: "tai",
  },
  {
    kanji: "同",
    meanings: ["same"],
    hiragana: "どう",
    romanji: "dou",
  },
  {
    kanji: "体",
    meanings: ["body"],
    hiragana: "からだ",
    romanji: "karada",
  },
  {
    kanji: "名",
    meanings: ["name", "fame"],
    hiragana: "な",
    romanji: "na",
  },
  {
    kanji: "目",
    meanings: ["eye"],
    hiragana: "め",
    romanji: "me",
  },
  {
    kanji: "段",
    meanings: ["step", "grade"],
    hiragana: "だん",
    romanji: "dan",
  },
  {
    kanji: "天",
    meanings: ["heaven", "sky"],
    hiragana: "てん",
    romanji: "ten",
  },
  {
    kanji: "割",
    meanings: ["divide", "cut"],
    hiragana: "わる",
    romanji: "waru",
  },
  {
    kanji: "完",
    meanings: ["complete", "finish"],
    hiragana: "かん",
    romanji: "kan",
  },
  {
    kanji: "研",
    meanings: ["sharpen", "research"],
    hiragana: "けん",
    romanji: "ken",
  },
  {
    kanji: "削",
    meanings: ["shave", "reduce"],
    hiragana: "けずる",
    romanji: "kezuru",
  },
  {
    kanji: "線",
    meanings: ["line"],
    hiragana: "せん",
    romanji: "sen",
  },
  {
    kanji: "造",
    meanings: ["make", "build"],
    hiragana: "つくる",
    romanji: "tsukuru",
  },
  {
    kanji: "提",
    meanings: ["propose", "present"],
    hiragana: "てい",
    romanji: "tei",
  },
  {
    kanji: "算",
    meanings: ["calculate", "count"],
    hiragana: "さん",
    romanji: "san",
  },
  {
    kanji: "氏",
    meanings: ["family name", "clan"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "川",
    meanings: ["river"],
    hiragana: "かわ",
    romanji: "kawa",
  },
  {
    kanji: "朝",
    meanings: ["morning"],
    hiragana: "あさ",
    romanji: "asa",
  },
  {
    kanji: "覚",
    meanings: ["remember", "wake up"],
    hiragana: "おぼえる",
    romanji: "oboeru",
  },
  {
    kanji: "管",
    meanings: ["pipe", "control"],
    hiragana: "かん",
    romanji: "kan",
  },
  {
    kanji: "系",
    meanings: ["system", "lineage"],
    hiragana: "けい",
    romanji: "kei",
  },
  {
    kanji: "師",
    meanings: ["teacher", "master"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "述",
    meanings: ["state", "express"],
    hiragana: "じゅつ",
    romanji: "jutsu",
  },
  {
    kanji: "運",
    meanings: ["carry", "luck"],
    hiragana: "うん",
    romanji: "un",
  },
  {
    kanji: "帰",
    meanings: ["return", "go home"],
    hiragana: "かえる",
    romanji: "kaeru",
  },
  {
    kanji: "職",
    meanings: ["job", "profession"],
    hiragana: "しょく",
    romanji: "shoku",
  },
  {
    kanji: "声",
    meanings: ["voice"],
    hiragana: "こえ",
    romanji: "koe",
  },
  {
    kanji: "増",
    meanings: ["increase", "add"],
    hiragana: "ふえる",
    romanji: "fueru",
  },
  {
    kanji: "島",
    meanings: ["island"],
    hiragana: "しま",
    romanji: "shima",
  },
  {
    kanji: "映",
    meanings: ["reflect", "project"],
    hiragana: "うつす",
    romanji: "utsusu",
  },
  {
    kanji: "換",
    meanings: ["exchange", "swap"],
    hiragana: "かえる",
    romanji: "kaeru",
  },
  {
    kanji: "観",
    meanings: ["view", "observe"],
    hiragana: "かん",
    romanji: "kan",
  },
  {
    kanji: "張",
    meanings: ["stretch", "spread"],
    hiragana: "はる",
    romanji: "haru",
  },
  {
    kanji: "死",
    meanings: ["death"],
    hiragana: "しぬ",
    romanji: "shinu",
  },
  {
    kanji: "習",
    meanings: ["learn", "practice"],
    hiragana: "ならう",
    romanji: "narau",
  },
  {
    kanji: "乗",
    meanings: ["ride", "board"],
    hiragana: "のる",
    romanji: "noru",
  },
  {
    kanji: "著",
    meanings: ["write", "author"],
    hiragana: "あらわす",
    romanji: "arawasu",
  },
  {
    kanji: "都",
    meanings: ["capital", "metropolis"],
    hiragana: "と",
    romanji: "to",
  },
  {
    kanji: "役",
    meanings: ["role", "duty"],
    hiragana: "やく",
    romanji: "yaku",
  },
  {
    kanji: "了",
    meanings: ["finish", "complete"],
    hiragana: "りょう",
    romanji: "ryou",
  },
  {
    kanji: "各",
    meanings: ["each", "every"],
    hiragana: "かく",
    romanji: "kaku",
  },
  {
    kanji: "個",
    meanings: ["individual", "counter"],
    hiragana: "こ",
    romanji: "ko",
  },
  {
    kanji: "写",
    meanings: ["copy", "photograph"],
    hiragana: "しゃ",
    romanji: "sha",
  },
  {
    kanji: "美",
    meanings: ["beauty"],
    hiragana: "び",
    romanji: "bi",
  },
  {
    kanji: "議",
    meanings: ["deliberate", "discuss"],
    hiragana: "ぎ",
    romanji: "gi",
  },
  {
    kanji: "雑",
    meanings: ["miscellaneous", "mixed"],
    hiragana: "ざつ",
    romanji: "zatsu",
  },
  {
    kanji: "親",
    meanings: ["parent", "intimate"],
    hiragana: "しん",
    romanji: "shin",
  },
  {
    kanji: "西",
    meanings: ["west"],
    hiragana: "にし",
    romanji: "nishi",
  },
  {
    kanji: "足",
    meanings: ["foot", "sufficient"],
    hiragana: "あし",
    romanji: "ashi",
  },
  {
    kanji: "安",
    meanings: ["peaceful", "cheap"],
    hiragana: "やすい",
    romanji: "yasui",
  },
  {
    kanji: "価",
    meanings: ["value", "price"],
    hiragana: "か",
    romanji: "ka",
  },
  {
    kanji: "視",
    meanings: ["look", "regard"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "専",
    meanings: ["exclusive", "specialized"],
    hiragana: "せん",
    romanji: "sen",
  },
  {
    kanji: "販",
    meanings: ["sell", "trade"],
    hiragana: "はん",
    romanji: "han",
  },
  {
    kanji: "務",
    meanings: ["task", "duty"],
    hiragana: "む",
    romanji: "mu",
  },
  {
    kanji: "予",
    meanings: ["beforehand", "in advance"],
    hiragana: "よ",
    romanji: "yo",
  },
  {
    kanji: "歌",
    meanings: ["song", "sing"],
    hiragana: "うた",
    romanji: "uta",
  },
  {
    kanji: "顔",
    meanings: ["face"],
    hiragana: "かお",
    romanji: "kao",
  },
  {
    kanji: "係",
    meanings: ["charge", "relation"],
    hiragana: "かかり",
    romanji: "kakari",
  },
  {
    kanji: "住",
    meanings: ["live", "dwell"],
    hiragana: "すむ",
    romanji: "sumu",
  },
  {
    kanji: "登",
    meanings: ["climb", "ascend"],
    hiragana: "のぼる",
    romanji: "noboru",
  },
  {
    kanji: "比",
    meanings: ["compare"],
    hiragana: "ひ",
    romanji: "hi",
  },
  {
    kanji: "約",
    meanings: ["promise", "approximately"],
    hiragana: "やく",
    romanji: "yaku",
  },
  {
    kanji: "介",
    meanings: ["mediate", "intervene"],
    hiragana: "かい",
    romanji: "kai",
  },
  {
    kanji: "簡",
    meanings: ["simple", "easy"],
    hiragana: "かん",
    romanji: "kan",
  },
  {
    kanji: "区",
    meanings: ["district", "ward"],
    hiragana: "く",
    romanji: "ku",
  },
  {
    kanji: "索",
    meanings: ["search", "rope"],
    hiragana: "さく",
    romanji: "saku",
  },
  {
    kanji: "象",
    meanings: ["elephant", "image"],
    hiragana: "ぞう",
    romanji: "zou",
  },
  {
    kanji: "側",
    meanings: ["side", "edge"],
    hiragana: "そば",
    romanji: "soba",
  },
  {
    kanji: "等",
    meanings: ["equal", "etc"],
    hiragana: "とう",
    romanji: "tou",
  },
  {
    kanji: "与",
    meanings: ["give", "grant"],
    hiragana: "あたえる",
    romanji: "ataeru",
  },
  {
    kanji: "量",
    meanings: ["quantity", "measure"],
    hiragana: "りょう",
    romanji: "ryou",
  },
  {
    kanji: "許",
    meanings: ["permit", "allow"],
    hiragana: "きょ",
    romanji: "kyo",
  },
  {
    kanji: "古",
    meanings: ["old", "ancient"],
    hiragana: "ふるい",
    romanji: "furui",
  },
  {
    kanji: "積",
    meanings: ["accumulate", "pile"],
    hiragana: "つむ",
    romanji: "tsumu",
  },
  {
    kanji: "半",
    meanings: ["half"],
    hiragana: "はん",
    romanji: "han",
  },
  {
    kanji: "便",
    meanings: ["convenience", "mail"],
    hiragana: "べん",
    romanji: "ben",
  },
  {
    kanji: "悪",
    meanings: ["bad", "evil"],
    hiragana: "わるい",
    romanji: "warui",
  },
  {
    kanji: "囲",
    meanings: ["surround"],
    hiragana: "かこむ",
    romanji: "kakomu",
  },
  {
    kanji: "工",
    meanings: ["construction", "craft"],
    hiragana: "こう",
    romanji: "kou",
  },
  {
    kanji: "深",
    meanings: ["deep"],
    hiragana: "ふかい",
    romanji: "fukai",
  },
  {
    kanji: "適",
    meanings: ["suitable"],
    hiragana: "てき",
    romanji: "teki",
  },
  {
    kanji: "念",
    meanings: ["thought", "concern"],
    hiragana: "ねん",
    romanji: "nen",
  },
  {
    kanji: "毎",
    meanings: ["every"],
    hiragana: "まい",
    romanji: "mai",
  },
  {
    kanji: "夜",
    meanings: ["night"],
    hiragana: "よる",
    romanji: "yoru",
  },
  {
    kanji: "演",
    meanings: ["perform", "act"],
    hiragana: "えん",
    romanji: "en",
  },
  {
    kanji: "拡",
    meanings: ["expand", "enlarge"],
    hiragana: "かく",
    romanji: "kaku",
  },
  {
    kanji: "器",
    meanings: ["container", "tool"],
    hiragana: "うつわ",
    romanji: "utsuwa",
  },
  {
    kanji: "域",
    meanings: ["region", "area"],
    hiragana: "いき",
    romanji: "iki",
  },
  {
    kanji: "右",
    meanings: ["right"],
    hiragana: "みぎ",
    romanji: "migi",
  },
  {
    kanji: "押",
    meanings: ["push", "press"],
    hiragana: "おす",
    romanji: "osu",
  },
  {
    kanji: "刊",
    meanings: ["publish", "print"],
    hiragana: "かん",
    romanji: "kan",
  },
  {
    kanji: "境",
    meanings: ["boundary", "border"],
    hiragana: "さかい",
    romanji: "sakai",
  },
  {
    kanji: "型",
    meanings: ["type", "model"],
    hiragana: "かた",
    romanji: "kata",
  },
  {
    kanji: "順",
    meanings: ["order", "sequence"],
    hiragana: "じゅん",
    romanji: "jun",
  },
  {
    kanji: "節",
    meanings: ["node", "season"],
    hiragana: "せつ",
    romanji: "setsu",
  },
  {
    kanji: "太",
    meanings: ["fat", "thick"],
    hiragana: "ふとい",
    romanji: "futoi",
  },
  {
    kanji: "断",
    meanings: ["cut off", "refuse"],
    hiragana: "だん",
    romanji: "dan",
  },
  {
    kanji: "般",
    meanings: ["general"],
    hiragana: "はん",
    romanji: "han",
  },
  {
    kanji: "英",
    meanings: ["English", "brave"],
    hiragana: "えい",
    romanji: "ei",
  },
  {
    kanji: "円",
    meanings: ["circle", "yen"],
    hiragana: "えん",
    romanji: "en",
  },
  {
    kanji: "温",
    meanings: ["warm"],
    hiragana: "おん",
    romanji: "on",
  },
  {
    kanji: "花",
    meanings: ["flower"],
    hiragana: "はな",
    romanji: "hana",
  },
  {
    kanji: "治",
    meanings: ["govern", "heal"],
    hiragana: "ち",
    romanji: "chi",
  },
  {
    kanji: "飛",
    meanings: ["fly"],
    hiragana: "とぶ",
    romanji: "tobu",
  },
  {
    kanji: "戻",
    meanings: ["return", "restore"],
    hiragana: "もどる",
    romanji: "modoru",
  },
  {
    kanji: "旅",
    meanings: ["trip", "travel"],
    hiragana: "たび",
    romanji: "tabi",
  },
  {
    kanji: "扱",
    meanings: ["handle", "deal with"],
    hiragana: "あつかう",
    romanji: "atsukau",
  },
  {
    kanji: "営",
    meanings: ["manage", "operate"],
    hiragana: "えい",
    romanji: "ei",
  },
  {
    kanji: "改",
    meanings: ["reform", "change"],
    hiragana: "かい",
    romanji: "kai",
  },
  {
    kanji: "御",
    meanings: ["honorable"],
    hiragana: "ご",
    romanji: "go",
  },
  {
    kanji: "再",
    meanings: ["again", "re-"],
    hiragana: "さい",
    romanji: "sai",
  },
  {
    kanji: "室",
    meanings: ["room"],
    hiragana: "しつ",
    romanji: "shitsu",
  },
  {
    kanji: "商",
    meanings: ["commerce", "trade"],
    hiragana: "しょう",
    romanji: "shou",
  },
  {
    kanji: "任",
    meanings: ["duty", "responsibility"],
    hiragana: "にん",
    romanji: "nin",
  },
  {
    kanji: "複",
    meanings: ["duplicate", "complex"],
    hiragana: "ふく",
    romanji: "fuku",
  },
  {
    kanji: "米",
    meanings: ["rice", "America"],
    hiragana: "べい",
    romanji: "bei",
  },
  {
    kanji: "優",
    meanings: ["superior", "gentle"],
    hiragana: "ゆう",
    romanji: "yuu",
  },
  {
    kanji: "愛",
    meanings: ["love"],
    hiragana: "あい",
    romanji: "ai",
  },
  {
    kanji: "座",
    meanings: ["sit"],
    hiragana: "ざ",
    romanji: "za",
  },
  {
    kanji: "細",
    meanings: ["thin", "narrow"],
    hiragana: "ほそい",
    romanji: "hosoi",
  },
  {
    kanji: "消",
    meanings: ["extinguish", "erase"],
    hiragana: "しょう",
    romanji: "shou",
  },
  {
    kanji: "争",
    meanings: ["contest", "argue"],
    hiragana: "あらそう",
    romanji: "arasou",
  },
  {
    kanji: "展",
    meanings: ["expand", "spread"],
    hiragana: "てん",
    romanji: "ten",
  },
  {
    kanji: "北",
    meanings: ["north"],
    hiragana: "きた",
    romanji: "kita",
  },
  {
    kanji: "落",
    meanings: ["fall", "drop"],
    hiragana: "おちる",
    romanji: "ochiru",
  },
  {
    kanji: "領",
    meanings: ["territory", "domain"],
    hiragana: "りょう",
    romanji: "ryou",
  },
  {
    kanji: "移",
    meanings: ["move", "shift"],
    hiragana: "うつる",
    romanji: "utsuru",
  },
  {
    kanji: "架",
    meanings: ["construct", "suspend"],
    hiragana: "かける",
    romanji: "kakeru",
  },
  {
    kanji: "景",
    meanings: ["view", "scenery"],
    hiragana: "けい",
    romanji: "kei",
  },
  {
    kanji: "献",
    meanings: ["offer", "present"],
    hiragana: "けん",
    romanji: "ken",
  },
  {
    kanji: "紙",
    meanings: ["paper"],
    hiragana: "かみ",
    romanji: "kami",
  },
  {
    kanji: "若",
    meanings: ["young", "if"],
    hiragana: "わかい",
    romanji: "wakai",
  },
  {
    kanji: "証",
    meanings: ["proof", "evidence"],
    hiragana: "しょう",
    romanji: "shou",
  },
  {
    kanji: "製",
    meanings: ["manufacture", "make"],
    hiragana: "せい",
    romanji: "sei",
  },
  {
    kanji: "操",
    meanings: ["operate", "control"],
    hiragana: "そう",
    romanji: "sou",
  },
  {
    kanji: "並",
    meanings: ["line up", "ordinary"],
    hiragana: "ならぶ",
    romanji: "narabu",
  },
  {
    kanji: "友",
    meanings: ["friend"],
    hiragana: "とも",
    romanji: "tomo",
  },
  {
    kanji: "客",
    meanings: ["guest", "customer"],
    hiragana: "きゃく",
    romanji: "kyaku",
  },
  {
    kanji: "誌",
    meanings: ["magazine", "document"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "早",
    meanings: ["early", "fast"],
    hiragana: "はやい",
    romanji: "hayai",
  },
  {
    kanji: "蔵",
    meanings: ["store", "warehouse"],
    hiragana: "くら",
    romanji: "kura",
  },
  {
    kanji: "程",
    meanings: ["extent", "degree"],
    hiragana: "てい",
    romanji: "tei",
  },
  {
    kanji: "転",
    meanings: ["turn", "revolve"],
    hiragana: "ころぶ",
    romanji: "korobu",
  },
  {
    kanji: "土",
    meanings: ["earth", "soil"],
    hiragana: "つち",
    romanji: "tsuchi",
  },
  {
    kanji: "統",
    meanings: ["unify", "rule"],
    hiragana: "とう",
    romanji: "tou",
  },
  {
    kanji: "納",
    meanings: ["pay", "store"],
    hiragana: "のう",
    romanji: "nou",
  },
  {
    kanji: "抜",
    meanings: ["extract", "pull out"],
    hiragana: "ぬく",
    romanji: "nuku",
  },
  {
    kanji: "非",
    meanings: ["negative", "non-"],
    hiragana: "ひ",
    romanji: "hi",
  },
  {
    kanji: "億",
    meanings: ["hundred million"],
    hiragana: "おく",
    romanji: "oku",
  },
  {
    kanji: "吉",
    meanings: ["good luck", "fortune"],
    hiragana: "きち",
    romanji: "kichi",
  },
  {
    kanji: "交",
    meanings: ["intersect", "mix"],
    hiragana: "こう",
    romanji: "kou",
  },
  {
    kanji: "総",
    meanings: ["total", "general"],
    hiragana: "そう",
    romanji: "sou",
  },
  {
    kanji: "探",
    meanings: ["search", "explore"],
    hiragana: "さがす",
    romanji: "sagasu",
  },
  {
    kanji: "標",
    meanings: ["mark", "standard"],
    hiragana: "ひょう",
    romanji: "hyou",
  },
  {
    kanji: "僕",
    meanings: ["I", "me"],
    hiragana: "ぼく",
    romanji: "boku",
  },
  {
    kanji: "未",
    meanings: ["not yet", "un-"],
    hiragana: "み",
    romanji: "mi",
  },
  {
    kanji: "紀",
    meanings: ["chronicle", "account"],
    hiragana: "き",
    romanji: "ki",
  },
  {
    kanji: "去",
    meanings: ["go", "leave"],
    hiragana: "さる",
    romanji: "saru",
  },
  {
    kanji: "県",
    meanings: ["prefecture"],
    hiragana: "けん",
    romanji: "ken",
  },
  {
    kanji: "千",
    meanings: ["thousand"],
    hiragana: "せん",
    romanji: "sen",
  },
  {
    kanji: "速",
    meanings: ["fast", "speed"],
    hiragana: "はやい",
    romanji: "hayai",
  },
  {
    kanji: "背",
    meanings: ["back", "height"],
    hiragana: "せ",
    romanji: "se",
  },
  {
    kanji: "歴",
    meanings: ["history", "passage"],
    hiragana: "れき",
    romanji: "reki",
  },
  {
    kanji: "路",
    meanings: ["road", "path"],
    hiragana: "みち",
    romanji: "michi",
  },
  {
    kanji: "影",
    meanings: ["shadow", "image"],
    hiragana: "かげ",
    romanji: "kage",
  },
  {
    kanji: "居",
    meanings: ["reside", "exist"],
    hiragana: "い",
    romanji: "i",
  },
  {
    kanji: "建",
    meanings: ["build", "construct"],
    hiragana: "たてる",
    romanji: "tateru",
  },
  {
    kanji: "台",
    meanings: ["stand", "platform"],
    hiragana: "だい",
    romanji: "dai",
  },
  {
    kanji: "誰",
    meanings: ["who"],
    hiragana: "だれ",
    romanji: "dare",
  },
  {
    kanji: "普",
    meanings: ["general", "universal"],
    hiragana: "ふ",
    romanji: "fu",
  },
  {
    kanji: "院",
    meanings: ["institution", "hospital"],
    hiragana: "いん",
    romanji: "in",
  },
  {
    kanji: "局",
    meanings: ["office", "department"],
    hiragana: "きょく",
    romanji: "kyoku",
  },
  {
    kanji: "苦",
    meanings: ["suffering", "pain"],
    hiragana: "く",
    romanji: "ku",
  },
  {
    kanji: "繰",
    meanings: ["spin", "reel"],
    hiragana: "くり",
    romanji: "kuri",
  },
  {
    kanji: "査",
    meanings: ["inspect", "investigate"],
    hiragana: "さ",
    romanji: "sa",
  },
  {
    kanji: "整",
    meanings: ["organize", "arrange"],
    hiragana: "せい",
    romanji: "sei",
  },
  {
    kanji: "装",
    meanings: ["equip", "dress"],
    hiragana: "そう",
    romanji: "sou",
  },
  {
    kanji: "答",
    meanings: ["answer", "respond"],
    hiragana: "こたえる",
    romanji: "kotaeru",
  },
  {
    kanji: "独",
    meanings: ["alone", "Germany"],
    hiragana: "どく",
    romanji: "doku",
  },
  {
    kanji: "難",
    meanings: ["difficult", "trouble"],
    hiragana: "なん",
    romanji: "nan",
  },
  {
    kanji: "離",
    meanings: ["separate", "leave"],
    hiragana: "はなれる",
    romanji: "hanareru",
  },
  {
    kanji: "異",
    meanings: ["different", "strange"],
    hiragana: "い",
    romanji: "i",
  },
  {
    kanji: "海",
    meanings: ["sea", "ocean"],
    hiragana: "うみ",
    romanji: "umi",
  },
  {
    kanji: "興",
    meanings: ["interest", "excitement"],
    hiragana: "きょう",
    romanji: "kyou",
  },
  {
    kanji: "極",
    meanings: ["extreme", "pole"],
    hiragana: "きょく",
    romanji: "kyoku",
  },
  {
    kanji: "根",
    meanings: ["root", "base"],
    hiragana: "ね",
    romanji: "ne",
  },
  {
    kanji: "済",
    meanings: ["settle", "finish"],
    hiragana: "さい",
    romanji: "sai",
  },
  {
    kanji: "修",
    meanings: ["repair", "discipline"],
    hiragana: "しゅう",
    romanji: "shuu",
  },
  {
    kanji: "紹",
    meanings: ["introduce"],
    hiragana: "しょう",
    romanji: "shou",
  },
  {
    kanji: "挿",
    meanings: ["insert"],
    hiragana: "そう",
    romanji: "sou",
  },
  {
    kanji: "福",
    meanings: ["fortune", "blessing"],
    hiragana: "ふく",
    romanji: "fuku",
  },
  {
    kanji: "印",
    meanings: ["mark", "seal"],
    hiragana: "いん",
    romanji: "in",
  },
  {
    kanji: "横",
    meanings: ["horizontal", "side"],
    hiragana: "よこ",
    romanji: "yoko",
  },
  {
    kanji: "火",
    meanings: ["fire"],
    hiragana: "ひ",
    romanji: "hi",
  },
  {
    kanji: "含",
    meanings: ["include", "contain"],
    hiragana: "ふくむ",
    romanji: "fukumu",
  },
  {
    kanji: "寄",
    meanings: ["approach", "gather"],
    hiragana: "よる",
    romanji: "yoru",
  },
  {
    kanji: "頃",
    meanings: ["time", "about"],
    hiragana: "ころ",
    romanji: "koro",
  },
  {
    kanji: "支",
    meanings: ["support", "branch"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "精",
    meanings: ["refine", "spirit"],
    hiragana: "せい",
    romanji: "sei",
  },
  {
    kanji: "庭",
    meanings: ["garden", "yard"],
    hiragana: "にわ",
    romanji: "niwa",
  },
  {
    kanji: "負",
    meanings: ["lose", "carry"],
    hiragana: "まける",
    romanji: "makeru",
  },
  {
    kanji: "環",
    meanings: ["ring", "circle"],
    hiragana: "かん",
    romanji: "kan",
  },
  {
    kanji: "失",
    meanings: ["lose", "fault"],
    hiragana: "しつ",
    romanji: "shitsu",
  },
  {
    kanji: "築",
    meanings: ["construct", "build"],
    hiragana: "ちく",
    romanji: "chiku",
  },
  {
    kanji: "茶",
    meanings: ["tea"],
    hiragana: "ちゃ",
    romanji: "cha",
  },
  {
    kanji: "途",
    meanings: ["way", "road"],
    hiragana: "と",
    romanji: "to",
  },
  {
    kanji: "遊",
    meanings: ["play", "amuse"],
    hiragana: "あそぶ",
    romanji: "asobu",
  },
  {
    kanji: "案",
    meanings: ["idea", "plan"],
    hiragana: "あん",
    romanji: "an",
  },
  {
    kanji: "巻",
    meanings: ["scroll", "volume"],
    hiragana: "かん",
    romanji: "kan",
  },
  {
    kanji: "況",
    meanings: ["condition", "situation"],
    hiragana: "きょう",
    romanji: "kyou",
  },
  {
    kanji: "載",
    meanings: ["publish", "record"],
    hiragana: "さい",
    romanji: "sai",
  },
  {
    kanji: "止",
    meanings: ["stop"],
    hiragana: "とまる",
    romanji: "tomaru",
  },
  {
    kanji: "昭",
    meanings: ["shine", "bright"],
    hiragana: "しょう",
    romanji: "shou",
  },
  {
    kanji: "省",
    meanings: ["omit", "reflect"],
    hiragana: "しょう",
    romanji: "shou",
  },
  {
    kanji: "石",
    meanings: ["stone"],
    hiragana: "いし",
    romanji: "ishi",
  },
  {
    kanji: "絶",
    meanings: ["discontinue", "cut off"],
    hiragana: "ぜつ",
    romanji: "zetsu",
  },
  {
    kanji: "率",
    meanings: ["rate", "ratio"],
    hiragana: "りつ",
    romanji: "ritsu",
  },
  {
    kanji: "両",
    meanings: ["both"],
    hiragana: "りょう",
    romanji: "ryou",
  },
  {
    kanji: "越",
    meanings: ["cross", "exceed"],
    hiragana: "こす",
    romanji: "kosu",
  },
  {
    kanji: "階",
    meanings: ["stairs", "floor"],
    hiragana: "かい",
    romanji: "kai",
  },
  {
    kanji: "急",
    meanings: ["urgent", "steep"],
    hiragana: "きゅう",
    romanji: "kyuu",
  },
  {
    kanji: "幸",
    meanings: ["happiness", "luck"],
    hiragana: "しあわせ",
    romanji: "shiawase",
  },
  {
    kanji: "項",
    meanings: ["item", "paragraph"],
    hiragana: "こう",
    romanji: "kou",
  },
  {
    kanji: "冊",
    meanings: ["book", "volume"],
    hiragana: "さつ",
    romanji: "satsu",
  },
  {
    kanji: "司",
    meanings: ["director", "manage"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "姿",
    meanings: ["figure", "shape"],
    hiragana: "すがた",
    romanji: "sugata",
  },
  {
    kanji: "守",
    meanings: ["protect", "defend"],
    hiragana: "まもる",
    romanji: "mamoru",
  },
  {
    kanji: "緒",
    meanings: ["beginning", "cord"],
    hiragana: "しょ",
    romanji: "sho",
  },
  {
    kanji: "青",
    meanings: ["blue", "green"],
    hiragana: "あお",
    romanji: "ao",
  },
  {
    kanji: "折",
    meanings: ["fold", "break"],
    hiragana: "おる",
    romanji: "oru",
  },
  {
    kanji: "泉",
    meanings: ["spring", "fountain"],
    hiragana: "いずみ",
    romanji: "izumi",
  },
  {
    kanji: "走",
    meanings: ["run"],
    hiragana: "はしる",
    romanji: "hashiru",
  },
  {
    kanji: "替",
    meanings: ["replace", "exchange"],
    hiragana: "かえる",
    romanji: "kaeru",
  },
  {
    kanji: "担",
    meanings: ["carry", "bear"],
    hiragana: "になう",
    romanji: "ninau",
  },
  {
    kanji: "遅",
    meanings: ["late", "slow"],
    hiragana: "おそい",
    romanji: "osoi",
  },
  {
    kanji: "町",
    meanings: ["town", "block"],
    hiragana: "まち",
    romanji: "machi",
  },
  {
    kanji: "聴",
    meanings: ["listen", "hear"],
    hiragana: "きく",
    romanji: "kiku",
  },
  {
    kanji: "渡",
    meanings: ["cross", "hand over"],
    hiragana: "わたる",
    romanji: "wataru",
  },
  {
    kanji: "費",
    meanings: ["expense", "spend"],
    hiragana: "ひ",
    romanji: "hi",
  },
  {
    kanji: "描",
    meanings: ["draw", "paint"],
    hiragana: "えがく",
    romanji: "egaku",
  },
  {
    kanji: "婦",
    meanings: ["woman", "wife"],
    hiragana: "ふ",
    romanji: "fu",
  },
  {
    kanji: "陽",
    meanings: ["sun", "yang"],
    hiragana: "よう",
    romanji: "you",
  },
  {
    kanji: "王",
    meanings: ["king"],
    hiragana: "おう",
    romanji: "ou",
  },
  {
    kanji: "戸",
    meanings: ["door", "household"],
    hiragana: "と",
    romanji: "to",
  },
  {
    kanji: "降",
    meanings: ["descend", "fall"],
    hiragana: "ふる",
    romanji: "furu",
  },
  {
    kanji: "左",
    meanings: ["left"],
    hiragana: "ひだり",
    romanji: "hidari",
  },
  {
    kanji: "週",
    meanings: ["week"],
    hiragana: "しゅう",
    romanji: "shuu",
  },
  {
    kanji: "測",
    meanings: ["measure", "survey"],
    hiragana: "はかる",
    romanji: "hakaru",
  },
  {
    kanji: "村",
    meanings: ["village"],
    hiragana: "むら",
    romanji: "mura",
  },
  {
    kanji: "倒",
    meanings: ["fall", "collapse"],
    hiragana: "たおれる",
    romanji: "taoreru",
  },
  {
    kanji: "導",
    meanings: ["guide", "lead"],
    hiragana: "みちびく",
    romanji: "michibiku",
  },
  {
    kanji: "敗",
    meanings: ["defeat", "lose"],
    hiragana: "やぶれる",
    romanji: "yabureru",
  },
  {
    kanji: "範",
    meanings: ["pattern", "model"],
    hiragana: "はん",
    romanji: "han",
  },
  {
    kanji: "筆",
    meanings: ["brush", "writing"],
    hiragana: "ふで",
    romanji: "fude",
  },
  {
    kanji: "武",
    meanings: ["warrior", "military"],
    hiragana: "ぶ",
    romanji: "bu",
  },
  {
    kanji: "末",
    meanings: ["end", "tip"],
    hiragana: "すえ",
    romanji: "sue",
  },
  {
    kanji: "満",
    meanings: ["full", "satisfied"],
    hiragana: "みちる",
    romanji: "michiru",
  },
  {
    kanji: "夢",
    meanings: ["dream"],
    hiragana: "ゆめ",
    romanji: "yume",
  },
  {
    kanji: "練",
    meanings: ["practice", "train"],
    hiragana: "ねる",
    romanji: "neru",
  },
  {
    kanji: "額",
    meanings: ["forehead", "sum"],
    hiragana: "がく",
    romanji: "gaku",
  },
  {
    kanji: "響",
    meanings: ["echo", "sound"],
    hiragana: "ひびく",
    romanji: "hibiku",
  },
  {
    kanji: "護",
    meanings: ["protect", "defend"],
    hiragana: "ご",
    romanji: "go",
  },
  {
    kanji: "施",
    meanings: ["carry out", "perform"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "似",
    meanings: ["resemble", "similar"],
    hiragana: "にる",
    romanji: "niru",
  },
  {
    kanji: "春",
    meanings: ["spring"],
    hiragana: "はる",
    romanji: "haru",
  },
  {
    kanji: "赤",
    meanings: ["red"],
    hiragana: "あか",
    romanji: "aka",
  },
  {
    kanji: "草",
    meanings: ["grass", "plant"],
    hiragana: "くさ",
    romanji: "kusa",
  },
  {
    kanji: "息",
    meanings: ["breath", "son"],
    hiragana: "いき",
    romanji: "iki",
  },
  {
    kanji: "働",
    meanings: ["work", "labor"],
    hiragana: "はたらく",
    romanji: "hataraku",
  },
  {
    kanji: "百",
    meanings: ["hundred"],
    hiragana: "ひゃく",
    romanji: "hyaku",
  },
  {
    kanji: "暮",
    meanings: ["live", "dwell"],
    hiragana: "くらす",
    romanji: "kurasu",
  },
  {
    kanji: "頼",
    meanings: ["rely", "request"],
    hiragana: "たのむ",
    romanji: "tanomu",
  },
  {
    kanji: "憶",
    meanings: ["recollection", "memory"],
    hiragana: "おく",
    romanji: "oku",
  },
  {
    kanji: "害",
    meanings: ["harm", "injury"],
    hiragana: "がい",
    romanji: "gai",
  },
  {
    kanji: "差",
    meanings: ["difference", "distinction"],
    hiragana: "さ",
    romanji: "sa",
  },
  {
    kanji: "寺",
    meanings: ["temple"],
    hiragana: "てら",
    romanji: "tera",
  },
  {
    kanji: "松",
    meanings: ["pine tree"],
    hiragana: "まつ",
    romanji: "matsu",
  },
  {
    kanji: "寝",
    meanings: ["sleep", "lie down"],
    hiragana: "ねる",
    romanji: "neru",
  },
  {
    kanji: "静",
    meanings: ["quiet", "calm"],
    hiragana: "しずか",
    romanji: "shizuka",
  },
  {
    kanji: "打",
    meanings: ["hit", "strike"],
    hiragana: "うつ",
    romanji: "utsu",
  },
  {
    kanji: "低",
    meanings: ["low", "short"],
    hiragana: "ひくい",
    romanji: "hikui",
  },
  {
    kanji: "弟",
    meanings: ["younger brother"],
    hiragana: "おとうと",
    romanji: "otouto",
  },
  {
    kanji: "努",
    meanings: ["effort", "endeavor"],
    hiragana: "つとめる",
    romanji: "tsutomeru",
  },
  {
    kanji: "馬",
    meanings: ["horse"],
    hiragana: "うま",
    romanji: "uma",
  },
  {
    kanji: "雨",
    meanings: ["rain"],
    hiragana: "あめ",
    romanji: "ame",
  },
  {
    kanji: "駅",
    meanings: ["station"],
    hiragana: "えき",
    romanji: "eki",
  },
  {
    kanji: "橋",
    meanings: ["bridge"],
    hiragana: "はし",
    romanji: "hashi",
  },
  {
    kanji: "驚",
    meanings: ["surprise", "astonish"],
    hiragana: "おどろく",
    romanji: "odoroku",
  },
  {
    kanji: "兄",
    meanings: ["older brother"],
    hiragana: "あに",
    romanji: "ani",
  },
  {
    kanji: "裁",
    meanings: ["judge", "decide"],
    hiragana: "さい",
    romanji: "sai",
  },
  {
    kanji: "策",
    meanings: ["plan", "policy"],
    hiragana: "さく",
    romanji: "saku",
  },
  {
    kanji: "周",
    meanings: ["circumference", "surround"],
    hiragana: "しゅう",
    romanji: "shuu",
  },
  {
    kanji: "詳",
    meanings: ["detailed", "precise"],
    hiragana: "くわしい",
    romanji: "kuwashii",
  },
  {
    kanji: "跡",
    meanings: ["trace", "mark"],
    hiragana: "あと",
    romanji: "ato",
  },
  {
    kanji: "属",
    meanings: ["belong", "affiliated"],
    hiragana: "ぞく",
    romanji: "zoku",
  },
  {
    kanji: "団",
    meanings: ["group", "organization"],
    hiragana: "だん",
    romanji: "dan",
  },
  {
    kanji: "疲",
    meanings: ["tired", "exhausted"],
    hiragana: "つかれる",
    romanji: "tsukareru",
  },
  {
    kanji: "評",
    meanings: ["evaluate", "critique"],
    hiragana: "ひょう",
    romanji: "hyou",
  },
  {
    kanji: "病",
    meanings: ["illness", "disease"],
    hiragana: "びょう",
    romanji: "byou",
  },
  {
    kanji: "忘",
    meanings: ["forget"],
    hiragana: "わすれる",
    romanji: "wasureru",
  },
  {
    kanji: "望",
    meanings: ["hope", "desire"],
    hiragana: "のぞむ",
    romanji: "nozomu",
  },
  {
    kanji: "核",
    meanings: ["core", "nucleus"],
    hiragana: "かく",
    romanji: "kaku",
  },
  {
    kanji: "危",
    meanings: ["danger", "risk"],
    hiragana: "あぶない",
    romanji: "abunai",
  },
  {
    kanji: "及",
    meanings: ["reach", "extend"],
    hiragana: "およぶ",
    romanji: "oyobu",
  },
  {
    kanji: "発",
    meanings: ["departure", "emit"],
    hiragana: "はつ",
    romanji: "hatsu",
  },
  {
    kanji: "知",
    meanings: ["know", "knowledge"],
    hiragana: "しる",
    romanji: "shiru",
  },
  {
    kanji: "部",
    meanings: ["part", "section"],
    hiragana: "ぶ",
    romanji: "bu",
  },
  {
    kanji: "法",
    meanings: ["law", "method"],
    hiragana: "ほう",
    romanji: "hou",
  },
  {
    kanji: "最",
    meanings: ["most", "extreme"],
    hiragana: "さい",
    romanji: "sai",
  },
  {
    kanji: "後",
    meanings: ["after", "later"],
    hiragana: "あと",
    romanji: "ato",
  },
  {
    kanji: "報",
    meanings: ["report", "news"],
    hiragana: "ほう",
    romanji: "hou",
  },
  {
    kanji: "面",
    meanings: ["face", "surface"],
    hiragana: "めん",
    romanji: "men",
  },
  {
    kanji: "利",
    meanings: ["profit", "benefit"],
    hiragana: "り",
    romanji: "ri",
  },
  {
    kanji: "通",
    meanings: ["pass", "communicate"],
    hiragana: "つう",
    romanji: "tsuu",
  },
  {
    kanji: "当",
    meanings: ["hit", "appropriate"],
    hiragana: "とう",
    romanji: "tou",
  },
  {
    kanji: "来",
    meanings: ["come", "next"],
    hiragana: "くる",
    romanji: "kuru",
  },
  {
    kanji: "化",
    meanings: ["change", "transform"],
    hiragana: "か",
    romanji: "ka",
  },
  {
    kanji: "取",
    meanings: ["take", "receive"],
    hiragana: "とる",
    romanji: "toru",
  },
  {
    kanji: "意",
    meanings: ["idea", "intention"],
    hiragana: "い",
    romanji: "i",
  },
  {
    kanji: "開",
    meanings: ["open", "begin"],
    hiragana: "かい",
    romanji: "kai",
  },
  {
    kanji: "持",
    meanings: ["hold", "possess"],
    hiragana: "もつ",
    romanji: "motsu",
  },
  {
    kanji: "高",
    meanings: ["tall", "high"],
    hiragana: "たかい",
    romanji: "takai",
  },
  {
    kanji: "情",
    meanings: ["emotion", "feelings"],
    hiragana: "じょう",
    romanji: "jou",
  },
  {
    kanji: "立",
    meanings: ["stand", "establish"],
    hiragana: "たつ",
    romanji: "tatsu",
  },
  {
    kanji: "挙",
    meanings: ["raise", "election"],
    hiragana: "きょ",
    romanji: "kyo",
  },
  {
    kanji: "継",
    meanings: ["inherit", "succeed"],
    hiragana: "けい",
    romanji: "kei",
  },
  {
    kanji: "射",
    meanings: ["shoot", "ray"],
    hiragana: "しゃ",
    romanji: "sha",
  },
  {
    kanji: "衆",
    meanings: ["masses", "crowd"],
    hiragana: "しゅう",
    romanji: "shuu",
  },
  {
    kanji: "植",
    meanings: ["plant", "grow"],
    hiragana: "うえる",
    romanji: "ueru",
  },
  {
    kanji: "責",
    meanings: ["blame", "responsibility"],
    hiragana: "せき",
    romanji: "seki",
  },
  {
    kanji: "雪",
    meanings: ["snow"],
    hiragana: "ゆき",
    romanji: "yuki",
  },
  {
    kanji: "創",
    meanings: ["create", "originate"],
    hiragana: "そう",
    romanji: "sou",
  },
  {
    kanji: "端",
    meanings: ["edge", "end"],
    hiragana: "はし",
    romanji: "hashi",
  },
  {
    kanji: "布",
    meanings: ["cloth", "spread"],
    hiragana: "ぬの",
    romanji: "nuno",
  },
  {
    kanji: "仏",
    meanings: ["Buddha", "France"],
    hiragana: "ぶつ",
    romanji: "butsu",
  },
  {
    kanji: "補",
    meanings: ["supplement", "assist"],
    hiragana: "ほ",
    romanji: "ho",
  },
  {
    kanji: "略",
    meanings: ["abbreviation", "strategy"],
    hiragana: "りゃく",
    romanji: "ryaku",
  },
  {
    kanji: "益",
    meanings: ["benefit", "profit"],
    hiragana: "えき",
    romanji: "eki",
  },
  {
    kanji: "絵",
    meanings: ["picture", "drawing"],
    hiragana: "え",
    romanji: "e",
  },
  {
    kanji: "級",
    meanings: ["rank", "grade"],
    hiragana: "きゅう",
    romanji: "kyuu",
  },
  {
    kanji: "激",
    meanings: ["fierce", "intense"],
    hiragana: "げき",
    romanji: "geki",
  },
  {
    kanji: "講",
    meanings: ["lecture", "explain"],
    hiragana: "こう",
    romanji: "kou",
  },
  {
    kanji: "従",
    meanings: ["obey", "follow"],
    hiragana: "じゅう",
    romanji: "juu",
  },
  {
    kanji: "焼",
    meanings: ["burn", "grill"],
    hiragana: "やく",
    romanji: "yaku",
  },
  {
    kanji: "笑",
    meanings: ["laugh", "smile"],
    hiragana: "わらう",
    romanji: "warau",
  },
  {
    kanji: "税",
    meanings: ["tax"],
    hiragana: "ぜい",
    romanji: "zei",
  },
  {
    kanji: "堂",
    meanings: ["hall", "temple"],
    hiragana: "どう",
    romanji: "dou",
  },
  {
    kanji: "派",
    meanings: ["faction", "group"],
    hiragana: "は",
    romanji: "ha",
  },
  {
    kanji: "因",
    meanings: ["cause", "factor"],
    hiragana: "いん",
    romanji: "in",
  },
  {
    kanji: "遠",
    meanings: ["far", "distant"],
    hiragana: "とおい",
    romanji: "tooi",
  },
  {
    kanji: "央",
    meanings: ["center", "central"],
    hiragana: "おう",
    romanji: "ou",
  },
  {
    kanji: "夏",
    meanings: ["summer"],
    hiragana: "なつ",
    romanji: "natsu",
  },
  {
    kanji: "我",
    meanings: ["I", "self"],
    hiragana: "われ",
    romanji: "ware",
  },
  {
    kanji: "較",
    meanings: ["compare"],
    hiragana: "こう",
    romanji: "kou",
  },
  {
    kanji: "休",
    meanings: ["rest", "break"],
    hiragana: "やすむ",
    romanji: "yasumu",
  },
  {
    kanji: "君",
    meanings: ["you", "lord"],
    hiragana: "きみ",
    romanji: "kimi",
  },
  {
    kanji: "減",
    meanings: ["decrease", "reduce"],
    hiragana: "へる",
    romanji: "heru",
  },
  {
    kanji: "撮",
    meanings: ["take (photo)", "record"],
    hiragana: "とる",
    romanji: "toru",
  },
  {
    kanji: "士",
    meanings: ["gentleman", "warrior"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "秋",
    meanings: ["autumn"],
    hiragana: "あき",
    romanji: "aki",
  },
  {
    kanji: "城",
    meanings: ["castle"],
    hiragana: "しろ",
    romanji: "shiro",
  },
  {
    kanji: "昔",
    meanings: ["old times", "long ago"],
    hiragana: "むかし",
    romanji: "mukashi",
  },
  {
    kanji: "則",
    meanings: ["rule", "regulation"],
    hiragana: "そく",
    romanji: "soku",
  },
  {
    kanji: "族",
    meanings: ["family", "tribe"],
    hiragana: "ぞく",
    romanji: "zoku",
  },
  {
    kanji: "沢",
    meanings: ["swamp", "marsh"],
    hiragana: "さわ",
    romanji: "sawa",
  },
  {
    kanji: "谷",
    meanings: ["valley"],
    hiragana: "たに",
    romanji: "tani",
  },
  {
    kanji: "南",
    meanings: ["south"],
    hiragana: "みなみ",
    romanji: "minami",
  },
  {
    kanji: "敷",
    meanings: ["spread", "lay out"],
    hiragana: "しく",
    romanji: "shiku",
  },
  {
    kanji: "兵",
    meanings: ["soldier", "army"],
    hiragana: "へい",
    romanji: "hei",
  },
  {
    kanji: "夕",
    meanings: ["evening"],
    hiragana: "ゆう",
    romanji: "yuu",
  },
  {
    kanji: "粒",
    meanings: ["grain", "drop"],
    hiragana: "つぶ",
    romanji: "tsubu",
  },
  {
    kanji: "角",
    meanings: ["horn", "angle"],
    hiragana: "かど",
    romanji: "kado",
  },
  {
    kanji: "官",
    meanings: ["government", "official"],
    hiragana: "かん",
    romanji: "kan",
  },
  {
    kanji: "協",
    meanings: ["cooperate", "work together"],
    hiragana: "きょう",
    romanji: "kyou",
  },
  {
    kanji: "恵",
    meanings: ["blessing", "favor"],
    hiragana: "めぐみ",
    romanji: "megumi",
  },
  {
    kanji: "察",
    meanings: ["observe", "guess"],
    hiragana: "さつ",
    romanji: "satsu",
  },
  {
    kanji: "請",
    meanings: ["request", "ask"],
    hiragana: "せい",
    romanji: "sei",
  },
  {
    kanji: "党",
    meanings: ["party", "faction"],
    hiragana: "とう",
    romanji: "tou",
  },
  {
    kanji: "如",
    meanings: ["as if", "like"],
    hiragana: "じょ",
    romanji: "jo",
  },
  {
    kanji: "秘",
    meanings: ["secret"],
    hiragana: "ひ",
    romanji: "hi",
  },
  {
    kanji: "富",
    meanings: ["wealth", "riches"],
    hiragana: "とみ",
    romanji: "tomi",
  },
  {
    kanji: "密",
    meanings: ["dense", "secret"],
    hiragana: "みつ",
    romanji: "mitsu",
  },
  {
    kanji: "薬",
    meanings: ["medicine", "drug"],
    hiragana: "くすり",
    romanji: "kusuri",
  },
  {
    kanji: "養",
    meanings: ["nurture", "foster"],
    hiragana: "やしなう",
    romanji: "yashinau",
  },
  {
    kanji: "労",
    meanings: ["labor", "work"],
    hiragana: "ろう",
    romanji: "rou",
  },
  {
    kanji: "医",
    meanings: ["doctor", "medicine"],
    hiragana: "い",
    romanji: "i",
  },
  {
    kanji: "奥",
    meanings: ["inner", "deep"],
    hiragana: "おく",
    romanji: "oku",
  },
  {
    kanji: "逆",
    meanings: ["reverse", "opposite"],
    hiragana: "ぎゃく",
    romanji: "gyaku",
  },
  {
    kanji: "遣",
    meanings: ["send", "dispatch"],
    hiragana: "けん",
    romanji: "ken",
  },
  {
    kanji: "険",
    meanings: ["dangerous", "steep"],
    hiragana: "けん",
    romanji: "ken",
  },
  {
    kanji: "皇",
    meanings: ["emperor"],
    hiragana: "こう",
    romanji: "kou",
  },
  {
    kanji: "香",
    meanings: ["fragrance", "aroma"],
    hiragana: "かおり",
    romanji: "kaori",
  },
  {
    kanji: "刻",
    meanings: ["engrave", "cut"],
    hiragana: "こく",
    romanji: "koku",
  },
  {
    kanji: "妻",
    meanings: ["wife"],
    hiragana: "つま",
    romanji: "tsuma",
  },
  {
    kanji: "志",
    meanings: ["will", "intention"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "宿",
    meanings: ["inn", "lodge"],
    hiragana: "しゅく",
    romanji: "shuku",
  },
  {
    kanji: "宣",
    meanings: ["declare", "proclaim"],
    hiragana: "せん",
    romanji: "sen",
  },
  {
    kanji: "洗",
    meanings: ["wash"],
    hiragana: "あらう",
    romanji: "arau",
  },
  {
    kanji: "眺",
    meanings: ["view", "gaze"],
    hiragana: "ながめる",
    romanji: "nagameru",
  },
  {
    kanji: "超",
    meanings: ["super", "transcend"],
    hiragana: "ちょう",
    romanji: "chou",
  },
  {
    kanji: "豆",
    meanings: ["bean", "pea"],
    hiragana: "まめ",
    romanji: "mame",
  },
  {
    kanji: "悲",
    meanings: ["sad", "sorrow"],
    hiragana: "かなしい",
    romanji: "kanashii",
  },
  {
    kanji: "抱",
    meanings: ["embrace", "hug"],
    hiragana: "だく",
    romanji: "daku",
  },
  {
    kanji: "踊",
    meanings: ["dance"],
    hiragana: "おどる",
    romanji: "odoru",
  },
  {
    kanji: "隠",
    meanings: ["hide", "conceal"],
    hiragana: "かくす",
    romanji: "kakusu",
  },
  {
    kanji: "岸",
    meanings: ["shore", "coast"],
    hiragana: "きし",
    romanji: "kishi",
  },
  {
    kanji: "喜",
    meanings: ["rejoice", "happy"],
    hiragana: "よろこぶ",
    romanji: "yorokobu",
  },
  {
    kanji: "刑",
    meanings: ["punishment", "penalty"],
    hiragana: "けい",
    romanji: "kei",
  },
  {
    kanji: "芸",
    meanings: ["art", "craft"],
    hiragana: "げい",
    romanji: "gei",
  },
  {
    kanji: "源",
    meanings: ["source", "origin"],
    hiragana: "みなもと",
    romanji: "minamoto",
  },
  {
    kanji: "互",
    meanings: ["mutual", "reciprocal"],
    hiragana: "ご",
    romanji: "go",
  },
  {
    kanji: "罪",
    meanings: ["crime", "sin"],
    hiragana: "つみ",
    romanji: "tsumi",
  },
  {
    kanji: "財",
    meanings: ["wealth", "fortune"],
    hiragana: "ざい",
    romanji: "zai",
  },
  {
    kanji: "札",
    meanings: ["bill", "note"],
    hiragana: "さつ",
    romanji: "satsu",
  },
  {
    kanji: "至",
    meanings: ["reach", "arrive"],
    hiragana: "いたる",
    romanji: "itaru",
  },
  {
    kanji: "首",
    meanings: ["neck", "head"],
    hiragana: "くび",
    romanji: "kubi",
  },
  {
    kanji: "助",
    meanings: ["help", "assist"],
    hiragana: "たすける",
    romanji: "tasukeru",
  },
  {
    kanji: "招",
    meanings: ["invite", "summon"],
    hiragana: "まねく",
    romanji: "maneku",
  },
  {
    kanji: "清",
    meanings: ["clean", "pure"],
    hiragana: "きよい",
    romanji: "kiyoi",
  },
  {
    kanji: "聖",
    meanings: ["holy", "sacred"],
    hiragana: "せい",
    romanji: "sei",
  },
  {
    kanji: "談",
    meanings: ["talk", "discuss"],
    hiragana: "だん",
    romanji: "dan",
  },
  {
    kanji: "藤",
    meanings: ["wisteria"],
    hiragana: "ふじ",
    romanji: "fuji",
  },
  {
    kanji: "突",
    meanings: ["thrust", "stab"],
    hiragana: "つく",
    romanji: "tsuku",
  },
  {
    kanji: "払",
    meanings: ["pay", "clear away"],
    hiragana: "はらう",
    romanji: "harau",
  },
  {
    kanji: "辺",
    meanings: ["area", "vicinity"],
    hiragana: "へん",
    romanji: "hen",
  },
  {
    kanji: "覧",
    meanings: ["look", "inspect"],
    hiragana: "らん",
    romanji: "ran",
  },
  {
    kanji: "圧",
    meanings: ["pressure", "press"],
    hiragana: "あつ",
    romanji: "atsu",
  },
  {
    kanji: "暗",
    meanings: ["dark", "gloomy"],
    hiragana: "くらい",
    romanji: "kurai",
  },
  {
    kanji: "飲",
    meanings: ["drink"],
    hiragana: "のむ",
    romanji: "nomu",
  },
  {
    kanji: "荷",
    meanings: ["baggage", "load"],
    hiragana: "に",
    romanji: "ni",
  },
  {
    kanji: "鬼",
    meanings: ["demon", "ogre"],
    hiragana: "おに",
    romanji: "oni",
  },
  {
    kanji: "宮",
    meanings: ["palace", "shrine"],
    hiragana: "みや",
    romanji: "miya",
  },
  {
    kanji: "恐",
    meanings: ["fear", "dread"],
    hiragana: "おそれる",
    romanji: "osoreru",
  },
  {
    kanji: "健",
    meanings: ["healthy", "strong"],
    hiragana: "けん",
    romanji: "ken",
  },
  {
    kanji: "砂",
    meanings: ["sand"],
    hiragana: "すな",
    romanji: "suna",
  },
  {
    kanji: "殺",
    meanings: ["kill", "murder"],
    hiragana: "ころす",
    romanji: "korosu",
  },
  {
    kanji: "星",
    meanings: ["star", "planet"],
    hiragana: "ほし",
    romanji: "hoshi",
  },
  {
    kanji: "席",
    meanings: ["seat", "position"],
    hiragana: "せき",
    romanji: "seki",
  },
  {
    kanji: "善",
    meanings: ["good", "virtuous"],
    hiragana: "ぜん",
    romanji: "zen",
  },
  {
    kanji: "頂",
    meanings: ["top", "summit"],
    hiragana: "いただく",
    romanji: "itadaku",
  },
  {
    kanji: "投",
    meanings: ["throw", "cast"],
    hiragana: "なげる",
    romanji: "nageru",
  },
  {
    kanji: "農",
    meanings: ["agriculture"],
    hiragana: "のう",
    romanji: "nou",
  },
  {
    kanji: "備",
    meanings: ["prepare", "provide"],
    hiragana: "そなえる",
    romanji: "sonaeru",
  },
  {
    kanji: "訪",
    meanings: ["visit", "call on"],
    hiragana: "おとずれる",
    romanji: "otozureru",
  },
  {
    kanji: "油",
    meanings: ["oil"],
    hiragana: "あぶら",
    romanji: "abura",
  },
  {
    kanji: "欲",
    meanings: ["desire", "want"],
    hiragana: "ほしい",
    romanji: "hoshii",
  },
  {
    kanji: "老",
    meanings: ["old", "aged"],
    hiragana: "ろう",
    romanji: "rou",
  },
  {
    kanji: "郎",
    meanings: ["son", "man"],
    hiragana: "ろう",
    romanji: "rou",
  },
  {
    kanji: "岡",
    meanings: ["hill", "knoll"],
    hiragana: "おか",
    romanji: "oka",
  },
  {
    kanji: "街",
    meanings: ["street", "town"],
    hiragana: "まち",
    romanji: "machi",
  },
  {
    kanji: "掛",
    meanings: ["hang", "suspend"],
    hiragana: "かける",
    romanji: "kakeru",
  },
  {
    kanji: "巨",
    meanings: ["huge", "gigantic"],
    hiragana: "きょ",
    romanji: "kyo",
  },
  {
    kanji: "拠",
    meanings: ["base", "foundation"],
    hiragana: "きょ",
    romanji: "kyo",
  },
  {
    kanji: "競",
    meanings: ["compete", "contest"],
    hiragana: "きそう",
    romanji: "kisou",
  },
  {
    kanji: "句",
    meanings: ["phrase", "sentence"],
    hiragana: "く",
    romanji: "ku",
  },
  {
    kanji: "軍",
    meanings: ["army", "military"],
    hiragana: "ぐん",
    romanji: "gun",
  },
  {
    kanji: "携",
    meanings: ["carry", "hold"],
    hiragana: "けい",
    romanji: "kei",
  },
  {
    kanji: "警",
    meanings: ["alert", "warn"],
    hiragana: "けい",
    romanji: "kei",
  },
  {
    kanji: "軽",
    meanings: ["light", "easy"],
    hiragana: "かるい",
    romanji: "karui",
  },
  {
    kanji: "迎",
    meanings: ["welcome", "greet"],
    hiragana: "むかえる",
    romanji: "mukaeru",
  },
  {
    kanji: "午",
    meanings: ["noon"],
    hiragana: "ご",
    romanji: "go",
  },
  {
    kanji: "黒",
    meanings: ["black"],
    hiragana: "くろ",
    romanji: "kuro",
  },
  {
    kanji: "阪",
    meanings: ["slope", "hill"],
    hiragana: "さか",
    romanji: "saka",
  },
  {
    kanji: "捨",
    meanings: ["discard", "throw away"],
    hiragana: "すてる",
    romanji: "suteru",
  },
  {
    kanji: "振",
    meanings: ["shake", "wave"],
    hiragana: "ふる",
    romanji: "furu",
  },
  {
    kanji: "申",
    meanings: ["say", "declare"],
    hiragana: "もうす",
    romanji: "mousu",
  },
  {
    kanji: "析",
    meanings: ["analyze", "divide"],
    hiragana: "せき",
    romanji: "seki",
  },
  {
    kanji: "船",
    meanings: ["ship", "boat"],
    hiragana: "ふね",
    romanji: "fune",
  },
  {
    kanji: "退",
    meanings: ["retreat", "withdraw"],
    hiragana: "たい",
    romanji: "tai",
  },
  {
    kanji: "弾",
    meanings: ["bullet", "spring"],
    hiragana: "たま",
    romanji: "tama",
  },
  {
    kanji: "仲",
    meanings: ["relationship", "fellow"],
    hiragana: "なか",
    romanji: "naka",
  },
  {
    kanji: "博",
    meanings: ["exhibition", "wide knowledge"],
    hiragana: "はく",
    romanji: "haku",
  },
  {
    kanji: "閉",
    meanings: ["close", "shut"],
    hiragana: "しめる",
    romanji: "shimeru",
  },
  {
    kanji: "捕",
    meanings: ["capture", "arrest"],
    hiragana: "とらえる",
    romanji: "toraeru",
  },
  {
    kanji: "能",
    meanings: ["ability", "skill"],
    hiragana: "のう",
    romanji: "nou",
  },
  {
    kanji: "読",
    meanings: ["read"],
    hiragana: "よむ",
    romanji: "yomu",
  },
  {
    kanji: "向",
    meanings: ["facing", "towards"],
    hiragana: "むかう",
    romanji: "mukau",
  },
  {
    kanji: "解",
    meanings: ["solution", "understand"],
    hiragana: "かい",
    romanji: "kai",
  },
  {
    kanji: "加",
    meanings: ["add", "increase"],
    hiragana: "か",
    romanji: "ka",
  },
  {
    kanji: "近",
    meanings: ["near", "close"],
    hiragana: "ちかい",
    romanji: "chikai",
  },
  {
    kanji: "結",
    meanings: ["tie", "bind"],
    hiragana: "むすぶ",
    romanji: "musubu",
  },
  {
    kanji: "処",
    meanings: ["deal with", "place"],
    hiragana: "しょ",
    romanji: "sho",
  },
  {
    kanji: "問",
    meanings: ["question", "ask"],
    hiragana: "もん",
    romanji: "mon",
  },
  {
    kanji: "界",
    meanings: ["world", "boundary"],
    hiragana: "かい",
    romanji: "kai",
  },
  {
    kanji: "更",
    meanings: ["change", "renew"],
    hiragana: "さら",
    romanji: "sara",
  },
  {
    kanji: "続",
    meanings: ["continue", "sequel"],
    hiragana: "つづく",
    romanji: "tsuzuku",
  },
  {
    kanji: "計",
    meanings: ["plan", "measure"],
    hiragana: "けい",
    romanji: "kei",
  },
  {
    kanji: "主",
    meanings: ["main", "lord"],
    hiragana: "しゅ",
    romanji: "shu",
  },
  {
    kanji: "不",
    meanings: ["not", "negative"],
    hiragana: "ふ",
    romanji: "fu",
  },
  {
    kanji: "道",
    meanings: ["way", "path"],
    hiragana: "みち",
    romanji: "michi",
  },
  {
    kanji: "付",
    meanings: ["attach", "apply"],
    hiragana: "つける",
    romanji: "tsukeru",
  },
  {
    kanji: "在",
    meanings: ["exist", "be located"],
    hiragana: "ざい",
    romanji: "zai",
  },
  {
    kanji: "八",
    meanings: ["eight"],
    hiragana: "はち",
    romanji: "hachi",
  },
  {
    kanji: "択",
    meanings: ["choose", "select"],
    hiragana: "たく",
    romanji: "taku",
  },
  {
    kanji: "置",
    meanings: ["place", "put"],
    hiragana: "おく",
    romanji: "oku",
  },
  {
    kanji: "品",
    meanings: ["goods", "item"],
    hiragana: "しな",
    romanji: "shina",
  },
  {
    kanji: "回",
    meanings: ["rotate", "turn"],
    hiragana: "かい",
    romanji: "kai",
  },
  {
    kanji: "込",
    meanings: ["crowded", "include"],
    hiragana: "こむ",
    romanji: "komu",
  },
  {
    kanji: "屋",
    meanings: ["shop", "roof"],
    hiragana: "や",
    romanji: "ya",
  },
  {
    kanji: "違",
    meanings: ["differ", "wrong"],
    hiragana: "ちがう",
    romanji: "chigau",
  },
  {
    kanji: "金",
    meanings: ["gold", "money"],
    hiragana: "きん",
    romanji: "kin",
  },
  {
    kanji: "校",
    meanings: ["school"],
    hiragana: "こう",
    romanji: "kou",
  },
  {
    kanji: "神",
    meanings: ["god", "spirit"],
    hiragana: "かみ",
    romanji: "kami",
  },
  {
    kanji: "味",
    meanings: ["taste", "flavor"],
    hiragana: "あじ",
    romanji: "aji",
  },
  {
    kanji: "重",
    meanings: ["heavy", "important"],
    hiragana: "おもい",
    romanji: "omoi",
  },
  {
    kanji: "無",
    meanings: ["none", "nothing"],
    hiragana: "む",
    romanji: "mu",
  },
  {
    kanji: "点",
    meanings: ["point", "dot"],
    hiragana: "てん",
    romanji: "ten",
  },
  {
    kanji: "容",
    meanings: ["contain", "appearance"],
    hiragana: "よう",
    romanji: "you",
  },
  {
    kanji: "列",
    meanings: ["row", "line"],
    hiragana: "れつ",
    romanji: "retsu",
  },
  {
    kanji: "果",
    meanings: ["fruit", "result"],
    hiragana: "はたす",
    romanji: "hatasu",
  },
  {
    kanji: "仕",
    meanings: ["serve", "work"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "別",
    meanings: ["separate", "different"],
    hiragana: "べつ",
    romanji: "betsu",
  },
  {
    kanji: "単",
    meanings: ["single", "simple"],
    hiragana: "たん",
    romanji: "tan",
  },
  {
    kanji: "少",
    meanings: ["few", "little"],
    hiragana: "すくない",
    romanji: "sukunai",
  },
  {
    kanji: "常",
    meanings: ["usual", "regular"],
    hiragana: "じょう",
    romanji: "jou",
  },
  {
    kanji: "身",
    meanings: ["body", "oneself"],
    hiragana: "み",
    romanji: "mi",
  },
  {
    kanji: "強",
    meanings: ["strong", "force"],
    hiragana: "つよい",
    romanji: "tsuyoi",
  },
  {
    kanji: "版",
    meanings: ["edition", "printing"],
    hiragana: "はん",
    romanji: "han",
  },
  {
    kanji: "論",
    meanings: ["argument", "discussion"],
    hiragana: "ろん",
    romanji: "ron",
  },
  {
    kanji: "決",
    meanings: ["decide", "determine"],
    hiragana: "けつ",
    romanji: "ketsu",
  },
  {
    kanji: "説",
    meanings: ["explanation", "theory"],
    hiragana: "せつ",
    romanji: "setsu",
  },
  {
    kanji: "題",
    meanings: ["topic", "title"],
    hiragana: "だい",
    romanji: "dai",
  },
  {
    kanji: "式",
    meanings: ["ceremony", "style"],
    hiragana: "しき",
    romanji: "shiki",
  },
  {
    kanji: "得",
    meanings: ["gain", "acquire"],
    hiragana: "える",
    romanji: "eru",
  },
  {
    kanji: "他",
    meanings: ["other"],
    hiragana: "た",
    romanji: "ta",
  },
  {
    kanji: "値",
    meanings: ["value", "price"],
    hiragana: "あたい",
    romanji: "atai",
  },
  {
    kanji: "店",
    meanings: ["store", "shop"],
    hiragana: "みせ",
    romanji: "mise",
  },
  {
    kanji: "公",
    meanings: ["public", "official"],
    hiragana: "こう",
    romanji: "kou",
  },
  {
    kanji: "進",
    meanings: ["advance", "progress"],
    hiragana: "すすむ",
    romanji: "susumu",
  },
  {
    kanji: "然",
    meanings: ["so", "nature"],
    hiragana: "ぜん",
    romanji: "zen",
  },
  {
    kanji: "売",
    meanings: ["sell"],
    hiragana: "うる",
    romanji: "uru",
  },
  {
    kanji: "平",
    meanings: ["flat", "calm"],
    hiragana: "たいら",
    romanji: "taira",
  },
  {
    kanji: "料",
    meanings: ["fee", "material"],
    hiragana: "りょう",
    romanji: "ryou",
  },
  {
    kanji: "員",
    meanings: ["member", "employee"],
    hiragana: "いん",
    romanji: "in",
  },
  {
    kanji: "確",
    meanings: ["certain", "sure"],
    hiragana: "かく",
    romanji: "kaku",
  },
  {
    kanji: "食",
    meanings: ["eat", "food"],
    hiragana: "たべる",
    romanji: "taberu",
  },
  {
    kanji: "存",
    meanings: ["exist", "preserve"],
    hiragana: "そん",
    romanji: "son",
  },
  {
    kanji: "調",
    meanings: ["investigate", "tone"],
    hiragana: "ちょう",
    romanji: "chou",
  },
  {
    kanji: "活",
    meanings: ["life", "active"],
    hiragana: "かつ",
    romanji: "katsu",
  },
  {
    kanji: "起",
    meanings: ["rise", "wake up"],
    hiragana: "おきる",
    romanji: "okiru",
  },
  {
    kanji: "状",
    meanings: ["condition", "situation"],
    hiragana: "じょう",
    romanji: "jou",
  },
  {
    kanji: "葉",
    meanings: ["leaf"],
    hiragana: "は",
    romanji: "ha",
  },
  {
    kanji: "資",
    meanings: ["resources", "capital"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "素",
    meanings: ["element", "simple"],
    hiragana: "そ",
    romanji: "so",
  },
  {
    kanji: "電",
    meanings: ["electricity"],
    hiragana: "でん",
    romanji: "den",
  },
  {
    kanji: "連",
    meanings: ["connect", "lead"],
    hiragana: "れん",
    romanji: "ren",
  },
  {
    kanji: "権",
    meanings: ["right", "authority"],
    hiragana: "けん",
    romanji: "ken",
  },
  {
    kanji: "真",
    meanings: ["true", "real"],
    hiragana: "しん",
    romanji: "shin",
  },
  {
    kanji: "終",
    meanings: ["end"],
    hiragana: "おわる",
    romanji: "owaru",
  },
  {
    kanji: "応",
    meanings: ["respond", "apply"],
    hiragana: "おう",
    romanji: "ou",
  },
  {
    kanji: "除",
    meanings: ["remove", "exclude"],
    hiragana: "じょ",
    romanji: "jo",
  },
  {
    kanji: "信",
    meanings: ["believe", "trust"],
    hiragana: "しん",
    romanji: "shin",
  },
  {
    kanji: "可",
    meanings: ["can", "possible"],
    hiragana: "か",
    romanji: "ka",
  },
  {
    kanji: "色",
    meanings: ["color"],
    hiragana: "いろ",
    romanji: "iro",
  },
  {
    kanji: "像",
    meanings: ["image", "statue"],
    hiragana: "ぞう",
    romanji: "zou",
  },
  {
    kanji: "経",
    meanings: ["manage", "pass"],
    hiragana: "けい",
    romanji: "kei",
  },
  {
    kanji: "組",
    meanings: ["group", "assemble"],
    hiragana: "くみ",
    romanji: "kumi",
  },
  {
    kanji: "達",
    meanings: ["reach", "attain"],
    hiragana: "たつ",
    romanji: "tatsu",
  },
  {
    kanji: "例",
    meanings: ["example"],
    hiragana: "れい",
    romanji: "rei",
  },
  {
    kanji: "期",
    meanings: ["period", "time"],
    hiragana: "き",
    romanji: "ki",
  },
  {
    kanji: "好",
    meanings: ["like", "favor"],
    hiragana: "すき",
    romanji: "suki",
  },
  {
    kanji: "始",
    meanings: ["begin"],
    hiragana: "はじまる",
    romanji: "hajimaru",
  },
  {
    kanji: "配",
    meanings: ["distribute", "allocate"],
    hiragana: "はい",
    romanji: "hai",
  },
  {
    kanji: "形",
    meanings: ["shape", "form"],
    hiragana: "かたち",
    romanji: "katachi",
  },
  {
    kanji: "呼",
    meanings: ["call", "name"],
    hiragana: "よぶ",
    romanji: "yobu",
  },
  {
    kanji: "七",
    meanings: ["seven"],
    hiragana: "しち",
    romanji: "shichi",
  },
  {
    kanji: "流",
    meanings: ["flow", "current"],
    hiragana: "ながれる",
    romanji: "nagareru",
  },
  {
    kanji: "楽",
    meanings: ["music", "comfort"],
    hiragana: "がく",
    romanji: "gaku",
  },
  {
    kanji: "参",
    meanings: ["participate", "visit"],
    hiragana: "さん",
    romanji: "san",
  },
  {
    kanji: "車",
    meanings: ["car", "vehicle"],
    hiragana: "くるま",
    romanji: "kuruma",
  },
  {
    kanji: "号",
    meanings: ["number", "issue"],
    hiragana: "ごう",
    romanji: "gou",
  },
  {
    kanji: "六",
    meanings: ["six"],
    hiragana: "ろく",
    romanji: "roku",
  },
  {
    kanji: "構",
    meanings: ["structure", "construct"],
    hiragana: "こう",
    romanji: "kou",
  },
  {
    kanji: "収",
    meanings: ["obtain", "collect"],
    hiragana: "しゅう",
    romanji: "shuu",
  },
  {
    kanji: "追",
    meanings: ["chase", "follow"],
    hiragana: "おう",
    romanji: "ou",
  },
  {
    kanji: "野",
    meanings: ["field", "wild"],
    hiragana: "の",
    romanji: "no",
  },
  {
    kanji: "限",
    meanings: ["limit", "boundary"],
    hiragana: "げん",
    romanji: "gen",
  },
  {
    kanji: "基",
    meanings: ["basis", "foundation"],
    hiragana: "き",
    romanji: "ki",
  },
  {
    kanji: "相",
    meanings: ["mutual", "phase"],
    hiragana: "あい",
    romanji: "ai",
  },
  {
    kanji: "男",
    meanings: ["man", "male"],
    hiragana: "おとこ",
    romanji: "otoko",
  },
  {
    kanji: "風",
    meanings: ["wind", "style"],
    hiragana: "かぜ",
    romanji: "kaze",
  },
  {
    kanji: "求",
    meanings: ["request", "seek"],
    hiragana: "もとめる",
    romanji: "motomeru",
  },
  {
    kanji: "効",
    meanings: ["effect", "result"],
    hiragana: "こう",
    romanji: "kou",
  },
  {
    kanji: "彼",
    meanings: ["he", "him"],
    hiragana: "かれ",
    romanji: "kare",
  },
  {
    kanji: "返",
    meanings: ["return", "give back"],
    hiragana: "かえす",
    romanji: "kaesu",
  },
  {
    kanji: "田",
    meanings: ["field", "rice paddy"],
    hiragana: "た",
    romanji: "ta",
  },
  {
    kanji: "検",
    meanings: ["examine", "inspect"],
    hiragana: "けん",
    romanji: "ken",
  },
  {
    kanji: "術",
    meanings: ["art", "technique"],
    hiragana: "じゅつ",
    romanji: "jutsu",
  },
  {
    kanji: "反",
    meanings: ["oppose", "reverse"],
    hiragana: "はん",
    romanji: "han",
  },
  {
    kanji: "直",
    meanings: ["straight", "fix"],
    hiragana: "なおす",
    romanji: "naosu",
  },
  {
    kanji: "民",
    meanings: ["people", "nation"],
    hiragana: "みん",
    romanji: "min",
  },
  {
    kanji: "広",
    meanings: ["wide", "spread"],
    hiragana: "ひろい",
    romanji: "hiroi",
  },
  {
    kanji: "識",
    meanings: ["knowledge", "discrimination"],
    hiragana: "しき",
    romanji: "shiki",
  },
  {
    kanji: "制",
    meanings: ["system", "control"],
    hiragana: "せい",
    romanji: "sei",
  },
  {
    kanji: "判",
    meanings: ["judge", "discern"],
    hiragana: "はん",
    romanji: "han",
  },
  {
    kanji: "原",
    meanings: ["origin", "field"],
    hiragana: "げん",
    romanji: "gen",
  },
  {
    kanji: "水",
    meanings: ["water"],
    hiragana: "みず",
    romanji: "mizu",
  },
  {
    kanji: "送",
    meanings: ["send", "transmit"],
    hiragana: "そう",
    romanji: "sou",
  },
  {
    kanji: "伝",
    meanings: ["transmit", "communicate"],
    hiragana: "つたえる",
    romanji: "tsutaeru",
  },
  {
    kanji: "規",
    meanings: ["rule", "standard"],
    hiragana: "き",
    romanji: "ki",
  },
  {
    kanji: "件",
    meanings: ["matter", "affair"],
    hiragana: "けん",
    romanji: "ken",
  },
  {
    kanji: "元",
    meanings: ["origin", "basis"],
    hiragana: "もと",
    romanji: "moto",
  },
  {
    kanji: "政",
    meanings: ["politics", "government"],
    hiragana: "せい",
    romanji: "sei",
  },
  {
    kanji: "想",
    meanings: ["thought", "idea"],
    hiragana: "そう",
    romanji: "sou",
  },
  {
    kanji: "買",
    meanings: ["buy", "purchase"],
    hiragana: "かう",
    romanji: "kau",
  },
  {
    kanji: "科",
    meanings: ["course", "section"],
    hiragana: "か",
    romanji: "ka",
  },
  {
    kanji: "態",
    meanings: ["condition", "attitude"],
    hiragana: "たい",
    romanji: "tai",
  },
  {
    kanji: "万",
    meanings: ["ten thousand"],
    hiragana: "まん",
    romanji: "man",
  },
  {
    kanji: "材",
    meanings: ["material", "talent"],
    hiragana: "ざい",
    romanji: "zai",
  },
  {
    kanji: "木",
    meanings: ["tree", "wood"],
    hiragana: "き",
    romanji: "ki",
  },
  {
    kanji: "良",
    meanings: ["good", "fine"],
    hiragana: "よい",
    romanji: "yoi",
  },
  {
    kanji: "録",
    meanings: ["record", "register"],
    hiragana: "ろく",
    romanji: "roku",
  },
  {
    kanji: "市",
    meanings: ["city", "market"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "質",
    meanings: ["quality", "matter"],
    hiragana: "しつ",
    romanji: "shitsu",
  },
  {
    kanji: "受",
    meanings: ["receive", "accept"],
    hiragana: "うける",
    romanji: "ukeru",
  },
  {
    kanji: "待",
    meanings: ["wait", "anticipate"],
    hiragana: "まつ",
    romanji: "matsu",
  },
  {
    kanji: "白",
    meanings: ["white"],
    hiragana: "しろ",
    romanji: "shiro",
  },
  {
    kanji: "編",
    meanings: ["compile", "edit"],
    hiragana: "へん",
    romanji: "hen",
  },
  {
    kanji: "歩",
    meanings: ["walk", "step"],
    hiragana: "あるく",
    romanji: "aruku",
  },
  {
    kanji: "歳",
    meanings: ["age", "year"],
    hiragana: "さい",
    romanji: "sai",
  },
  {
    kanji: "際",
    meanings: ["occasion", "edge"],
    hiragana: "さい",
    romanji: "sai",
  },
  {
    kanji: "産",
    meanings: ["produce", "give birth"],
    hiragana: "さん",
    romanji: "san",
  },
  {
    kanji: "放",
    meanings: ["release", "let go"],
    hiragana: "はなす",
    romanji: "hanasu",
  },
  {
    kanji: "音",
    meanings: ["sound", "noise"],
    hiragana: "おと",
    romanji: "oto",
  },
  {
    kanji: "格",
    meanings: ["status", "rank"],
    hiragana: "かく",
    romanji: "kaku",
  },
  {
    kanji: "企",
    meanings: ["plan", "project"],
    hiragana: "き",
    romanji: "ki",
  },
  {
    kanji: "空",
    meanings: ["sky", "empty"],
    hiragana: "そら",
    romanji: "sora",
  },
  {
    kanji: "条",
    meanings: ["article", "clause"],
    hiragana: "じょう",
    romanji: "jou",
  },
  {
    kanji: "頭",
    meanings: ["head", "top"],
    hiragana: "あたま",
    romanji: "atama",
  },
  {
    kanji: "由",
    meanings: ["reason", "cause"],
    hiragana: "ゆう",
    romanji: "yuu",
  },
  {
    kanji: "類",
    meanings: ["type", "kind"],
    hiragana: "るい",
    romanji: "rui",
  },
  {
    kanji: "究",
    meanings: ["investigate", "research"],
    hiragana: "きゅう",
    romanji: "kyuu",
  },
  {
    kanji: "供",
    meanings: ["offer", "supply"],
    hiragana: "きょう",
    romanji: "kyou",
  },
  {
    kanji: "告",
    meanings: ["announce", "inform"],
    hiragana: "こく",
    romanji: "koku",
  },
  {
    kanji: "残",
    meanings: ["remain", "leftover"],
    hiragana: "のこる",
    romanji: "nokoru",
  },
  {
    kanji: "夫",
    meanings: ["husband"],
    hiragana: "おっと",
    romanji: "otto",
  },
  {
    kanji: "父",
    meanings: ["father"],
    hiragana: "ちち",
    romanji: "chichi",
  },
  {
    kanji: "接",
    meanings: ["touch", "connect"],
    hiragana: "せつ",
    romanji: "setsu",
  },
  {
    kanji: "着",
    meanings: ["arrive", "wear"],
    hiragana: "きる",
    romanji: "kiru",
  },
  {
    kanji: "認",
    meanings: ["acknowledge", "recognize"],
    hiragana: "みとめる",
    romanji: "mitomeru",
  },
  {
    kanji: "位",
    meanings: ["rank", "position"],
    hiragana: "くらい",
    romanji: "kurai",
  },
  {
    kanji: "光",
    meanings: ["light", "shine"],
    hiragana: "ひかり",
    romanji: "hikari",
  },
  {
    kanji: "史",
    meanings: ["history"],
    hiragana: "し",
    romanji: "shi",
  },
  {
    kanji: "準",
    meanings: ["standard", "quasi"],
    hiragana: "じゅん",
    romanji: "jun",
  },
  {
    kanji: "注",
    meanings: ["pour", "note"],
    hiragana: "ちゅう",
    romanji: "chuu",
  },
  {
    kanji: "和",
    meanings: ["harmony", "peace"],
    hiragana: "わ",
    romanji: "wa",
  },
  {
    kanji: "過",
    meanings: ["pass", "exceed"],
    hiragana: "か",
    romanji: "ka",
  },
  {
    kanji: "義",
    meanings: ["righteousness", "justice"],
    hiragana: "ぎ",
    romanji: "gi",
  },
  {
    kanji: "京",
    meanings: ["capital"],
    hiragana: "きょう",
    romanji: "kyou",
  },
  {
    kanji: "種",
    meanings: ["seed", "species"],
    hiragana: "しゅ",
    romanji: "shu",
  },
  {
    kanji: "章",
    meanings: ["chapter", "badge"],
    hiragana: "しょう",
    romanji: "shou",
  },
  {
    kanji: "門",
    meanings: ["gate"],
    hiragana: "もん",
    romanji: "mon",
  },
  {
    kanji: "共",
    meanings: ["together", "common"],
    hiragana: "きょう",
    romanji: "kyou",
  },
  {
    kanji: "験",
    meanings: ["test", "experience"],
    hiragana: "けん",
    romanji: "ken",
  },
  {
    kanji: "口",
    meanings: ["mouth"],
    hiragana: "くち",
    romanji: "kuchi",
  },
  {
    kanji: "番",
    meanings: ["number", "turn"],
    hiragana: "ばん",
    romanji: "ban",
  },
  {
    kanji: "母",
    meanings: ["mother"],
    hiragana: "はは",
    romanji: "haha",
  },
  {
    kanji: "育",
    meanings: ["raise", "grow"],
    hiragana: "いく",
    romanji: "iku",
  },
  {
    kanji: "具",
    meanings: ["tool", "implement"],
    hiragana: "ぐ",
    romanji: "gu",
  },
  {
    kanji: "照",
    meanings: ["shine", "illuminate"],
    hiragana: "てる",
    romanji: "teru",
  },
  {
    kanji: "東",
    meanings: ["east"],
    hiragana: "ひがし",
    romanji: "higashi",
  },
  {
    kanji: "命",
    meanings: ["life", "fate"],
    hiragana: "いのち",
    romanji: "inochi",
  },
  {
    kanji: "技",
    meanings: ["skill", "technique"],
    hiragana: "ぎ",
    romanji: "gi",
  },
  {
    kanji: "銀",
    meanings: ["silver"],
    hiragana: "ぎん",
    romanji: "gin",
  },
];
export { kanji };
